apiVersion: v1
kind: Secret

metadata:
  name: mongodb-secret

type: Opaque

stringData:
  MONGO_URI: "mongodb+srv://vinaysg205_db_user:qoo5vTezwRPKo7fK@cluster0.mrxyt9t.mongodb.net/ats-db?retryWrites=true&w=majority&appName=Cluster0"