apiVersion: v1
kind: Service
metadata:
  name: eks-demo-service
spec:
  type: "{{ .values.service.type }}"
  selector:
    app: eks-demo
  ports:
    - port: "{{ .values.service.port }}"
      targetPort: 3000
