apiVersion: v1
kind: Service
metadata:
  name: eks-demo-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: eks-demo
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000